### ISSUE TITLE
EventDrops.html does not work

### ISSUE THREAD

**Issue by iBinJubair** [hoonzis/KoExtensions#5]
Uncaught TypeError: Unable to process binding "eventDrops: function (){return carSales }"
Message: ko.onwrap is not a function

**Comment by lrecknagel** [comment]
I have the same issue that EventDrops.html does not work but I´ve got no error in the console. So can you please fix that :)

**Comment by hoonzis** [comment]
Hi.
Sorry for that I was too busy lately, also I did some major changes to the way the library is structured (using require properly etc.) and just did not have time to port it.

Also EventDrops continues to develop: https://github.com/marmelab/EventDrops and they implemented some of the stuff that I did (you can pass in any function to determine the sizee and color of the drop) now, so it might really be better to use the original library.

I am only hesitating to keep the knockout wrapper in KoExtensions - which would only work if the original eventdrops would be referenced on side.

**Comment by lrecknagel** [comment]
Okay no problem and thanks for your reference to the new functions of https://github.com/marmelab/EventDrops. I can find the color option but is there already a size option for the events? I cant find it in the library?!

**Comment by hoonzis** [comment]
Ah, ok I was reading too fast, I thought they added a function for the size as well, it is really very easy too implement. The problem is that I did not fork it properly and I can't incorporate it back. What I would have to do a fork, then implement the size and pass it as pull request to them

and than just adding a wrapper for knockout to my library
so there is a bit to work :)
